### PR TITLE
Bookmark manager support for display of offset/size in either hex or dec

### PR DESCRIPTION
**Pull request by datasynergyuk**
Suggested improvement for bookmark manager. This allows offsets / size to be shown in either decimal or hex.

### CODE REVIEW

**Comment by jovibor** [comment]
The property dialog is also dependent here.
I think we must be consistent on this.

**Comment by datasynergyuk** [comment]
I agree it should be consistent. This is why I suggest the user has the ability to change between decimal / hex input. It is confusing for the user that the current Bookmark Manager always displays addresses / sizes in hex but data input without "0x" prefix is automatically treated as decimal. 

In the longer term, I would suggest using a common control for all numeric input. Following your feedback, I have made a control called [CNumericEditControl](https://github.com/datasynergyuk/CNumericEditControl) that supports binary/decimal/hex/octal input, clipboard support and uses a cue (or watermark) to remind the user which mode they are currently in. The control supports conversion from the current input mode to any other mode and also allows this to be changed at runtime (using the ChangeMode() method). Finally, the control avoids the PreTranslateMessgae() approach and should be compatible with the DLL version of HexCtrl. 

I would welcome the use of this control or something similar in HexCtrl. I would also welcome suggestions and improvements for the control itself.

**Comment by jovibor** [comment]
What i meant was that if you select decimal mode in bkm manager it must be reflected in the bkm properties dialog as well.

**Comment by datasynergyuk** [comment]
I have made the necessary changes and also taken the opportunity to update the data interpreter dialog so it works the same way. 

Overall, I would still prefer to use a common control for this rather than re-code the functionality in each dialog. This could lessen coding errors and make the UI still more consistent.

**Comment by jovibor** [comment]
Switch in properties dialog was unnecessary, just inheritance, extra code was removed.

**Pull request closed without merging**
